###########################################################
### Breeanna Personett's Portfolio Configuration
###########################################################

############################
# --- Required options --- #
############################

title: Breeanna Personett
author: Breeanna Personett

###############################################
# --- Navigation & Profile Settings --- #
###############################################

avatar: "/assets/img/pfp_web.jpg"
round-avatar: true

navbar-links:
  About Me: "aboutme"
  Education: "education"
  Experience: "experience"
  Projects: "projects"
  Skills: "skills"
  MSU Portfolio: "https://persone3.msu.domains/portfolio/"

#####################################
# --- Social Media & Contact --- #
#####################################

social-network-links:
  email: "persone3@msu.edu"
  phone: "734-808-2448"
  linkedin: "Breeanna (Bree) Personett"
  github: "persiebee"
  website: "https://persone3.msu.domains/portfolio/"

###########################
# --- Content Sections --- #
###########################

# Education
education:
  - institution: Michigan State University
    degree: Experience Architecture Major | Computer Science Minor
    year: 2023-2027
    details: "Combining design thinking with technical implementation. My background in culinary arts honed my ability to work under pressure and deliver polished results."

  - institution: Dexter High School
    degree: High School Diploma
    year: 2019-2023
    details: "Graduated summa cum laude. Attended Culinary Consortium in Saline."

# Experience
experience:
  - company: Menards
    role: Cashier
    year: 2023-Present
    details: "Handle transactions, assist customers, and maintain store organization."

  - company: Poke Poke Sushi Unrolled
    role: Counter Service & Food Prep
    year: 2023
    details: "Managed opening/closing procedures and provided excellent customer service."

  - company: COCO Tea
    role: Drink Maker
    year: 2023
    details: "Developed strong multitasking skills preparing beverages while maintaining cleanliness."

# Skills
skills:
  languages:
    - name: English
      level: Native
    - name: Japanese
      level: Learning
    - name: Python
      level: Semi-Proficient
    - name: C++
      level: Beginner

  technical:
    - name: HTML/CSS
      level: 65%
    - name: WordPress
      level: 95%
    - name: Adobe Suite
      level: 85%

###########################
# --- Theme Settings --- #
###########################

theme_skin: green
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#adc178"  # Purple accent
hover-col: "#6a994e"

# Footer
footer-col: "#F8F9FA"
footer-text-col: "#6C757D"
footer-link-col: "#5D3FD3"

######################################
# --- Technical Configuration --- #
######################################

# Don't modify below this line unless you know what you're doing
timezone: "America/Detroit"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

site-css:
  - "/assets/css/custom.css"
